### ISSUE TITLE
Piecemill Documentation

### ISSUE THREAD

**Issue by qdacsvx** [ptpham/piecemeal#1]
I appreciate the command line usage hints in the apps piecelog and cps and play. I would like a usage hint for the app piecemeal.
It accepts interactive commands "add", "ask", "build" - what is the syntax for these commands?

**Comment by ptpham** [comment]
Hi! Thanks for the interest. Piecemill was intended to provide multithreaded prover functionality to another process through the standard io streams to avoid needing a language specific binding. All commands must be prefixed by some string indicating the "game instance". "add" provides kif lines into a buffer. "build" compiles the previously added lines into a game. "ask" uses previous lines as inputs into the prover using the specified game instance. "done" will delete/clean up the instance. Here's an example input sequence:

1 add (<= (next ?x) (true ?x))
1 build
1 add (true a)
1 ask

The last output you should see is the following note that it also returns the inputs you give it:
1 (next a) (true a)

A word of warning on using this library is that it uses fixed width representations for propositions. This means that if a game has more than the maximum number of propositions for the current width, it will not behave correctly. You can either use the larger maximum width or you can perform some kind of check at runtime (not implemented) to choose between the larger and smaller versions.

**Comment by ptpham** [comment]
I've added the above text to the file. Let me know if you have any additional questions! =)
